const menu = [
  {
    id: 1,
    title: "Fluffy Pancakes",
    category: "breakfast",
    price: 15.99,
    img: "/images/item-1.jpeg",
    desc: "Deliciously soft buttermilk pancakes served with a generous drizzle of maple syrup and fresh fruit, perfect for a delightful morning treat.",
  },
  {
    id: 2,
    title: "Cheeseburger Meal",
    category: "lunch",
    price: 13.99,
    img: "/images/item-2.jpeg",
    desc: "Juicy double-stacked cheeseburger with crispy lettuce, fresh tomato, and a tangy special sauce, served with golden fries.",
  },
  {
    id: 3,
    title: "Strawberry Milkshake",
    category: "shakes",
    price: 6.99,
    img: "/images/item-3.jpeg",
    desc: "Rich and creamy chocolate milkshake topped with whipped cream and sprinkles, a sweet indulgence for any time of day.",
  },
  {
    id: 4,
    title: "Breakfast Platter",
    category: "breakfast",
    price: 20.99,
    img: "/images/item-4.jpeg",
    desc: "A hearty breakfast platter featuring scrambled eggs, crispy bacon, sausage, and golden hash browns, served with toast or biscuits.",
  },
  {
    id: 5,
    title: "Home Egg Sandwich",
    category: "lunch",
    price: 22.99,
    img: "/images/item-5.jpeg",
    desc: "Savory egg sandwich stacked with melted cheese, crispy bacon, and fresh avocado on a toasted brioche bun.",
  },
  {
    id: 6,
    title: "Oreo Delight Shake",
    category: "shakes",
    price: 18.99,
    img: "/images/item-6.jpeg",
    desc: "A creamy Oreo milkshake loaded with crushed cookies, topped with whipped cream, and an extra cookie for good measure.",
  },
  {
    id: 7,
    title: "Bacon & Eggs Combo",
    category: "breakfast",
    price: 8.99,
    img: "/images/item-7.jpeg",
    desc: "A classic breakfast combination of crispy bacon and sunny-side-up eggs, served with your choice of toast or pancakes.",
  },
  {
    id: 8,
    title: "All-American Burger",
    category: "lunch",
    price: 12.99,
    img: "/images/item-8.jpeg",
    desc: "A classic American burger with a beef patty, melted cheese, lettuce, tomato, and onions on a toasted sesame bun.",
  },
  {
    id: 9,
    title: "Berry Blast Smoothie",
    category: "shakes",
    price: 16.99,
    img: "/images/item-9.jpeg",
    desc: "A refreshing blend of strawberries, blueberries, and raspberries, creating a vibrant smoothie full of natural sweetness.",
  },
];

export default menu;
